export interface ChannelData {
  id?: string
  // 频道ID
  channelId?: string
  // 频道名称
  title?: string
  // 订阅者数量
  subscriberCount?: number
  // 视频数量
  videoCount?: number
  // 频道分类
  categories?: string
  // 频道描述
  description?: string
  // 频道内容
  content?: string
  // 频道缩略图URL
  thumbnailUrl?: string
  // 频道rss链接
  rssUrl?: string
  // 频道地区
  region?: string
  // 频道创建时间
  channelCreatedAt?: string
  // 频道是否启用YouTube合作伙伴计划
  hasYPP?: boolean
  // 数据创建时间
  createdAt?: string
  // 数据修改时间
  updatedAt?: string
}
